
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmjggjkxlrzcmdoxzgzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtamdnamt4bHJ6Y21kb3h6Z3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc1NDMsImV4cCI6MjA2OTkxMzU0M30.uh8zlc4I28JKCDNO8N6a6-5UbRsjreBhL_ggBdpVae8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Extend session to 30 days (30 * 24 * 60 * 60 seconds)
    tokenRefreshInterval: 30 * 24 * 60 * 60,
  }
});
